spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: tramites-backend
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: tramitesdb
  web:
    cors:
      allowed-origins: "*"

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

gcs:
  bucket-name: tramites-documentos-494314

logging:
  level:
    org:
      springframework:
        security: TRACE